# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.TextField(verbose_name='图书分类'),
        ),
    ]
