# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160817_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='称呼')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('content', models.CharField(max_length=140, verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Book', verbose_name='图书')),
            ],
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Blog_Comment',
        ),
    ]
